[2025-04-04T23:41:17.103+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T23:41:17.177+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.setup_environment manual__2025-04-04T23:41:11.937168+00:00 [queued]>
[2025-04-04T23:41:17.193+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.setup_environment manual__2025-04-04T23:41:11.937168+00:00 [queued]>
[2025-04-04T23:41:17.194+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-04T23:41:17.226+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): setup_environment> on 2025-04-04 23:41:11.937168+00:00
[2025-04-04T23:41:17.237+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T23:41:17.240+0000] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2025-04-04T23:41:17.243+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'setup_environment', 'manual__2025-04-04T23:41:11.937168+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp5kzs_lsf']
[2025-04-04T23:41:17.247+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask setup_environment
[2025-04-04T23:41:17.348+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.setup_environment manual__2025-04-04T23:41:11.937168+00:00 [running]> on host 969622a44a53
[2025-04-04T23:41:17.567+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='setup_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T23:41:11.937168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T23:41:11.937168+00:00'
[2025-04-04T23:41:17.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T23:41:17.644+0000] {tmdb_pipeline.py:1072} INFO - Preparando entorno para el pipeline TMDB...
[2025-04-04T23:41:17.645+0000] {tmdb_pipeline.py:1076} INFO - Directorio de salida creado: /opt/***/data/movie_analytics
[2025-04-04T23:41:17.647+0000] {tmdb_pipeline.py:1064} ERROR - Error al crear tablas en PostgreSQL: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-04T23:41:17.649+0000] {tmdb_pipeline.py:1065} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 957, in create_postgres_tables
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-04T23:41:17.650+0000] {tmdb_pipeline.py:1084} WARNING - Hubo problemas preparando el entorno, pero continuaremos
[2025-04-04T23:41:17.651+0000] {python.py:237} INFO - Done. Returned value was: setup_completed
[2025-04-04T23:41:17.651+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T23:41:17.688+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=setup_environment, execution_date=20250404T234111, start_date=20250404T234117, end_date=20250404T234117
[2025-04-04T23:41:17.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T23:41:17.752+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T23:41:17.753+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
