[2025-04-07T01:31:45.233+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T01:31:45.256+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_optimized.setup_environment manual__2025-04-07T01:31:41.064977+00:00 [queued]>
[2025-04-07T01:31:45.263+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_optimized.setup_environment manual__2025-04-07T01:31:41.064977+00:00 [queued]>
[2025-04-07T01:31:45.264+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-07T01:31:45.277+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): setup_environment> on 2025-04-07 01:31:41.064977+00:00
[2025-04-07T01:31:45.288+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T01:31:45.290+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2025-04-07T01:31:45.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_optimized', 'setup_environment', 'manual__2025-04-07T01:31:41.064977+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp1vjr8y34']
[2025-04-07T01:31:45.293+0000] {standard_task_runner.py:91} INFO - Job 342: Subtask setup_environment
[2025-04-07T01:31:45.340+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_optimized.setup_environment manual__2025-04-07T01:31:41.064977+00:00 [running]> on host 6add7c178f3f
[2025-04-07T01:31:45.444+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_optimized' AIRFLOW_CTX_TASK_ID='setup_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T01:31:41.064977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T01:31:41.064977+00:00'
[2025-04-07T01:31:45.445+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T01:31:45.480+0000] {tmdb_pipeline.py:1384} INFO - Preparando entorno para el pipeline TMDB...
[2025-04-07T01:31:45.481+0000] {tmdb_pipeline.py:1388} INFO - Directorio de salida creado: /opt/***/data/movie_analytics
[2025-04-07T01:31:45.483+0000] {tmdb_pipeline.py:1480} ERROR - Error al crear tablas en PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-07T01:31:45.487+0000] {tmdb_pipeline.py:1481} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1393, in setup_environment
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-07T01:31:45.487+0000] {tmdb_pipeline.py:1487} WARNING - Hubo problemas preparando el entorno, pero continuaremos
[2025-04-07T01:31:45.488+0000] {python.py:237} INFO - Done. Returned value was: setup_completed
[2025-04-07T01:31:45.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T01:31:45.710+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_optimized, task_id=setup_environment, execution_date=20250407T013141, start_date=20250407T013145, end_date=20250407T013145
[2025-04-07T01:31:45.759+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-07T01:31:45.788+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-07T01:31:45.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
