[2025-04-03T14:45:40.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-03T14:45:40.305+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T14:45:40.314+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T14:45:40.314+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-03T14:45:40.326+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-02 00:00:00+00:00
[2025-04-03T14:45:40.332+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-03T14:45:40.333+0000] {standard_task_runner.py:63} INFO - Started process 203 to run task
[2025-04-03T14:45:40.334+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline', 'generate_visualizations', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpwtpdwhy4']
[2025-04-03T14:45:40.336+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask generate_visualizations
[2025-04-03T14:45:40.383+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-02T00:00:00+00:00 [running]> on host 29a2839b1f8c
[2025-04-03T14:45:40.496+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-03T14:45:40.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-03T14:45:41.787+0000] {tmdb_pipeline.py:547} ERROR - Error al leer datos de PostgreSQL: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-03T14:45:42.642+0000] {tmdb_pipeline.py:620} INFO - Visualizaciones guardadas en /opt/***/data/movie_analytics/visualizations_20250403_144541
[2025-04-03T14:45:42.661+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/visualizations_20250403_144541
[2025-04-03T14:45:42.662+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-03T14:45:42.689+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline, task_id=generate_visualizations, execution_date=20250402T000000, start_date=20250403T144540, end_date=20250403T144542
[2025-04-03T14:45:42.752+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-03T14:45:42.786+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-03T14:45:42.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
