[2025-04-07T12:13:41.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T12:13:41.937+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-07T12:13:41.967+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-07T12:13:41.969+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-04-07T12:13:42.022+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-07 00:00:00+00:00
[2025-04-07T12:13:42.041+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1578) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T12:13:42.048+0000] {standard_task_runner.py:63} INFO - Started process 1580 to run task
[2025-04-07T12:13:42.049+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'generate_visualizations', 'scheduled__2025-04-07T00:00:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp3foy2vc8']
[2025-04-07T12:13:42.059+0000] {standard_task_runner.py:91} INFO - Job 490: Subtask generate_visualizations
[2025-04-07T12:13:42.240+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-07T00:00:00+00:00 [running]> on host 596ea260a4a0
[2025-04-07T12:13:42.602+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T00:00:00+00:00'
[2025-04-07T12:13:42.607+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T12:13:47.327+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T12:13:47.330+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tmdb_pipeline.py", line 1680, in generate_visualizations
    import plotly.express as px
ModuleNotFoundError: No module named 'plotly'
[2025-04-07T12:13:47.369+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tmdb_pipeline_streamlit, task_id=generate_visualizations, execution_date=20250407T000000, start_date=20250407T121341, end_date=20250407T121347
[2025-04-07T12:13:47.423+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 490 for task generate_visualizations (No module named 'plotly'; 1580)
[2025-04-07T12:13:47.514+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-07T12:13:47.641+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T12:13:47.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
