[2025-04-05T12:06:05.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:06:05.062+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.load_to_postgres scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T12:06:05.082+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.load_to_postgres scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T12:06:05.083+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-05T12:06:05.113+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-05 00:00:00+00:00
[2025-04-05T12:06:05.124+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1001) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-05T12:06:05.127+0000] {standard_task_runner.py:63} INFO - Started process 1003 to run task
[2025-04-05T12:06:05.128+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'load_to_postgres', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpuzruuq0j']
[2025-04-05T12:06:05.133+0000] {standard_task_runner.py:91} INFO - Job 275: Subtask load_to_postgres
[2025-04-05T12:06:05.222+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.load_to_postgres scheduled__2025-04-05T00:00:00+00:00 [running]> on host bb6ca4ffe8d9
[2025-04-05T12:06:05.405+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-05T12:06:05.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:06:05.487+0000] {tmdb_pipeline.py:1477} INFO - Leyendo 10 registros procesados para cargar en PostgreSQL
[2025-04-05T12:06:05.489+0000] {tmdb_pipeline.py:1106} ERROR - Error al crear tablas en PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-05T12:06:05.492+0000] {tmdb_pipeline.py:1107} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 999, in create_postgres_tables
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-05T12:06:05.494+0000] {tmdb_pipeline.py:1656} ERROR - Error al conectar o insertar en PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-05T12:06:05.496+0000] {tmdb_pipeline.py:1657} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1484, in load_to_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-05T12:06:05.497+0000] {tmdb_pipeline.py:1660} INFO - Intentando m√©todo alternativo: guardar resultados como CSV
[2025-04-05T12:06:05.505+0000] {tmdb_pipeline.py:1665} INFO - Resultados guardados en /opt/***/data/movie_analytics/results_data_v3.csv
[2025-04-05T12:06:05.506+0000] {python.py:237} INFO - Done. Returned value was: 0
[2025-04-05T12:06:05.507+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:06:05.544+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=load_to_postgres, execution_date=20250405T000000, start_date=20250405T120605, end_date=20250405T120605
[2025-04-05T12:06:05.602+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T12:06:05.646+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:06:05.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
